#!/bin/sh

echo "Running pre-commit checks..."

make check

if [ $? -ne 0 ]; then
  echo ""
  echo "Pre-commit checks failed. Commit aborted."
  echo "Fix the issues above and try again."
  exit 1
fi
